### ISSUE TITLE
(Bug) Dislike button is active and counts even if a user is signed out

### ISSUE THREAD

**Issue by glenlalo** [Anarios/return-youtube-dislike#268]
### Browser

Firefox

### Browser Version

95.0

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=2AouOPFyV8c

### What happened?

As the title says, the dislike button is active and counts even a user is not signed in. Clicking the like button does not increase the number of likes but decreases the dislikes. This is an unwanted behavior.

**Comment by DARKDRAGON532** [comment]
Issue is fixed, its not released to the mozilla addons store yet, you can either wait or load the extension manually https://www.smashingmagazine.com/2017/04/browser-extension-edge-chrome-firefox-opera-brave-vivaldi/#mozilla-firefox

**Comment by glenlalo** [comment]
@DARKDRAGON532 I've loaded the extension manually and the issue is not fixed. 
As implemented in the script, the function checkForSignInButton() works only if the YouTube language is English.

**Comment by DARKDRAGON532** [comment]
Thanks for telling us, must've slipped by us, fix will be added soon, sorry.

**Comment by glenlalo** [comment]
@DARKDRAGON532 I have created a PR with the fix.
