### ISSUE TITLE
(Bug): High CPU usage

### ISSUE THREAD

**Issue by AndnixSH** [Anarios/return-youtube-dislike#272]
### Browser

Google Chrome

### Browser Version

96.0.4664.45 (Officiel version) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.2

### Video link where you see the problem

N/A

### What happened?

I have noticed this extension that is using high cpu usage. As soon as i turn off the extension, it went away

This is kinda hard to reproduce because it happens randomly, i'm not even watching the video. perhaps running the browser for too long? Sorry, i forgot to make video about it. is there more info i need to provide?

**Comment by Anarios** [comment]
I think I know the reason. For some peoplel, for some reason, multiple instances of extension start. This causes the high CPU usage. Never happened to me - so can't test for sure, but the next release fixes it.

**Comment by Frontesque** [comment]
> I think I know the reason. For some peoplel, for some reason, multiple instances of extension start. This causes the high CPU usage. Never happened to me - so can't test for sure, but the next release fixes it.

A possible fix for this might be detecting if a variable that the script uses already exists? Obviously it would need more thought but just throwing out ideas

**Comment by Anarios** [comment]
should be fixed in 2.0

**Comment by BlueDo** [comment]
I'm on version 2.0.0.2 and still experiencing the same behavior. 
Toggling the extension off brings CPU down. 
After toggling on, CPU usage rises randomly after a while.

**Comment by Anarios** [comment]
For how long does it rise? There is around 10 sec period when extension confirms that you're not a bot - after that there should be no CPU usage.

**Comment by IcyFrogs** [comment]
Running on version 2.0.0.3
I noticed my CPU fans were louder than usual so I went to task manager, found the browser was working at 18%
As soon as I switched off this extension the usage went back down to 2%.

After 5 mins I switched the extension back on and watched a few videos and did a little browsing and the CPU is still low as normal so I have not worked out what is triggering it yet

**Comment by Anarios** [comment]
> Running on version 2.0.0.3 I noticed my CPU fans were louder than usual so I went to task manager, found the browser was working at 18% As soon as I switched off this extension the usage went back down to 2%.
> 
> After 5 mins I switched the extension back on and watched a few videos and did a little browsing and the CPU is still low as normal so I have not worked out what is triggering it yet

My thoughts is that the antibot check triggered it. But by design it should've never lasted more than 10 seconds

Version 2.0.0.3 is available as well which could improve it.

**Comment by JrRadiant** [comment]
Version 2.0.0.3 and can confirm that CPU usage is notoriously high.

It's OK for me except the 1 thing — how can I prove there's no any cryptomining funcs that's CPU oriented, like XMR mining?

**Comment by JrRadiant** [comment]
Still high CPU usage in version 2.0.0.3.

If you mining XMR guys just tell us, it's OK to know. Your great plugin deserves it, just confess.

**Comment by Anarios** [comment]
> Still high CPU usage in version 2.0.0.3.
> 
> If you mining XMR guys just tell us, it's OK to know. Your great plugin deserves it, just confess.

It's open source. And you see the source of extension installed in your browser. I kinda wish I was mining XMR on a million machines - but I don't. It's just a bug, sorry.

Also - a very easy way to get permanently banned from google if I attempted it.

**Comment by AndnixSH** [comment]
For me, i'm not getting any issues anymore after the fix

**Comment by IcyFrogs** [comment]
Hi, it happened again today, but it's not common, the last time it happened to me was when I posted my last comment here 22 days ago. I captured a video of it just now.
I am using Brave browser which is based on chromium

https://user-images.githubusercontent.com/92159377/148692078-e4b11f17-ec83-48fa-b150-dac714d51eea.mp4
