### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by chrism229** [Anarios/return-youtube-dislike#909]
Looks like there are NO dislikes showing on any YT video.

**Comment by Nickwiz** [comment]
Same here, but the API is OK so guess it's just about the UI/DOM, or perhaps one of the transport layers.

* https://returnyoutubedislike.com/help
* https://returnyoutubedislikeapi.com/votes?videoId=4nPTTcwt_SQ

**Comment by Chonkblonk** [comment]
Not working for me either.
On old version, 98.0.1

**Comment by gusakovs** [comment]
Issue already covered on the discord server. Wait for Mozilla to approve the update.

![image](https://github.com/Anarios/return-youtube-dislike/assets/16121344/2b8e49e1-b3bf-4424-9a7b-863ef8f995a5)

**Comment by stonefrango** [comment]
Can confirm 3.0.0.9 fixed this for me, where it had been broken before. Refreshed a video and saw the dislikes as expected.

**Comment by Extravi** [comment]
> Issue already covered on the discord server. Wait for Mozilla to approve the update.
> 
> ![image](https://user-images.githubusercontent.com/16121344/237224315-2b8e49e1-b3bf-4424-9a7b-863ef8f995a5.png)

🔥

**Comment by procobain** [comment]
And why is the version of USERSCRIPT not working? Shouldn't it be updated more quickly? It's checking version 3.1.1 and it still doesn't work...

Hugs.

**Comment by BobbyWibowo** [comment]
@procobain Update your userscript
The version that comes with the same fixes as browser extensions version 3.0.0.9 is userscript version 3.1.2
It came together in the same commit https://github.com/Anarios/return-youtube-dislike/commit/5c73825aadb81b6bf16cd5dff2b81a88562b6634

**Comment by arghanath007** [comment]
Waiting then for Mozilla. Still the dislikes not working.

**Comment by Nickwiz** [comment]
Yes, Mozilla can be slow, very slow this time though. Find it a bit strange as this is a well established extension with a minor version update and close to 500k users ... but have no idea how the queue system works on the review side. Used to be some sites where one got some ques IIRC, but can not find it. As they have such a myriad of communication channels it's hard to figure out the best places to go,; but a couple might be:

* https://discourse.mozilla.org/c/add-ons/35 
* https://chat.mozilla.org/ look in `#/room/#addons:mozilla.org` or `#/room/#addon-reviewers:mozilla.org` etc.

**Comment by Nickwiz** [comment]
And there it is public ;)

**Comment by qawasx** [comment]
I have Firefox Nightly 115a, and extension version 3.0.0.9 yet still it does not work.

**Comment by ilia-21** [comment]
I am using firefox 114.0b2 with RYD 3.0.0.9 and it does not work, although it logs response from API in the console

**Comment by qawasx** [comment]
I figured out why. I use this Style https://userstyles.world/style/6944/old-youtube-layout-in-2021-2022 with the extension stylus. If i deactivate it, it works. Any way around that? can i somehow modify that style?

**Comment by ilia-21** [comment]
> I figured out why. I use this Style https://userstyles.world/style/6944/old-youtube-layout-in-2021-2022 with the extension stylus. If i deactivate it, it works. Any way around that? can i somehow modify that style?

Oh, yeah, I had a similar theme. Disabling that theme fixes the issue. I think a different `querySelector `should be used for the theme

**Comment by qawasx** [comment]
i have no clue how any of this works. Can you tell me exactly what i need to change?

**Comment by qawasx** [comment]
Nooo, i fixed it. I had a very very old version of that style. It works now

**Comment by arghanath007** [comment]
Still not working for me. I am in the normal branch only. When coming?

**Comment by spidy2356** [comment]
not working for me. ratio bar doesn't appear and now the dislike no. also does not appear. what to do?
version:v3.0.0.9, using google chrome

**Comment by spidy2356** [comment]
> > not working for me. ratio bar doesn't appear and now the dislike no. also does not appear. what to do? version:v3.0.0.9, using google chrome
> 
> make sure it isn't conflicting with any other youtube extensions

yes it is...I found it. 
https://github.com/Anarios/return-youtube-dislike/issues/909#issuecomment-1545655069

**Comment by chrism229** [comment]
I see the extension has been updated today in Firefox to v.3.0.0.9 and it works!
